version: "3"
services:
  www:
    build: .
    entrypoint: ./cmd/www/www
    ports:
      - "5000:5000"
  api:
    build: .
    entrypoint: ./cmd/api/api
    ports:
      - "8080:8080"
    links:
      - profile
      - search
      - jaeger
  profile:
    build: .
    entrypoint: ./cmd/profile/profile
    links:
      - jaeger
  search:
    build: .
    entrypoint: ./cmd/search/search
    links:
      - geo
      - rate
      - jaeger
  geo:
    build: .
    entrypoint: ./cmd/geo/geo
    links:
      - jaeger
  rate:
    build: .
    entrypoint: ./cmd/rate/rate
    links:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "9411:9411"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
