www:
  build: ./cmd/www
  ports: 
    - "5000:5000"
api:
  build: ./cmd/api
  ports:
    - "8080:8080"
  links:
    - geo
    - profile
    - rate
geo:
  build: ./cmd/geo
profile:
  build: ./cmd/profile
rate:
  build: ./cmd/rate
