version: "3"
services:
  frontend:
    build: .
    entrypoint: demo --service=frontend
    ports:
      - "5000:8080"
    links:
      - jaeger
      - search
      - profile
    depends_on:
      - search
      - profile
  search:
    build: .
    entrypoint: demo --service=search
    links:
      - geo
      - rate
      - jaeger
  profile:
    build: .
    entrypoint: demo --service=profile
    links:
      - geo
      - rate
      - jaeger
  geo:
    build: .
    entrypoint: demo --service=geo
    links:
      - jaeger
  rate:
    build: .
    entrypoint: demo --service=rate
    links:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
