version: "3"
services:
  frontend:
    build: .
    entrypoint: frontend
    ports:
      - "5000:5000"
    links:
      - search
      - profile
      - jaeger
  profile:
    build: .
    entrypoint: profile
    links:
      - jaeger
  search:
    build: .
    entrypoint: search
    links:
      - geo
      - rate
      - jaeger
  geo:
    build: .
    entrypoint: geo
    links:
      - jaeger
  rate:
    build: .
    entrypoint: rate
    links:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "9411:9411"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
